title: ring0 # name of the site
author: Téo Haÿs # name of site's author
email: me@haysberg.io # email of site's author
url: https://ring0.haysberg.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Enter my kernel.
  <br/>
  <br/>
  Greetings. My name is Téo and I'm currently a student in Masters degree in Computer Science.
  I'm mainly interested in Libre and open source software.
  <br/>Other areas of interest are Politics (related to the interweb or not), and many other things.
  <br/><br/>Feel free to contact me by email. I always love to interact with people.

permalink: /:slug.html

# favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "haysberg" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "Back" # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag